
class ShipData(object):

    ENG_DESTROYER_DMG = 30
    ENG_DESTROYER_HP = 15
    ENG_DESTROYER_SPD = 4
    ENG_DESTROYER_NAME = 'Medea'

    ENG_CRUISER_DMG = 15
    ENG_CRUISER_HP = 30
    ENG_CRUISER_SPD = 3
    ENG_CRUISER_NAME = 'Weymouth'

    ENG_BATTLESHIP_DMG = 20
    ENG_BATTLESHIP_HP = 50
    ENG_BATTLESHIP_SPD = 2
    ENG_BATTLESHIP_NAME = 'Iron Duke'

    ENG_DESTROYER = (ENG_DESTROYER_DMG, ENG_DESTROYER_HP, ENG_DESTROYER_SPD, ENG_DESTROYER_NAME, )
    ENG_CRUISER = (ENG_CRUISER_DMG, ENG_CRUISER_HP, ENG_CRUISER_SPD, ENG_CRUISER_NAME, )
    ENG_BATTLESHIP = (ENG_BATTLESHIP_DMG, ENG_BATTLESHIP_HP, ENG_BATTLESHIP_SPD, ENG_BATTLESHIP_NAME, )

    GER_DESTROYER_DMG = 30
    GER_DESTROYER_HP = 15
    GER_DESTROYER_SPD = 4
    GER_DESTROYER_NAME = 'G-101'

    GER_CRUISER_DMG = 15
    GER_CRUISER_HP = 30
    GER_CRUISER_SPD = 3
    GER_CRUISER_NAME = 'Kolberg'

    GER_BATTLESHIP_DMG = 20
    GER_BATTLESHIP_HP = 50
    GER_BATTLESHIP_SPD = 2
    GER_BATTLESHIP_NAME = 'Koening'

    GER_DESTROYER = (GER_DESTROYER_DMG, GER_DESTROYER_HP, GER_DESTROYER_SPD, GER_DESTROYER_NAME, )
    GER_CRUISER = (GER_CRUISER_DMG, ENG_CRUISER_HP, GER_CRUISER_SPD, GER_CRUISER_NAME, )
    GER_BATTLESHIP = (GER_BATTLESHIP_DMG, GER_BATTLESHIP_HP, GER_BATTLESHIP_SPD, GER_BATTLESHIP_NAME, )
